#!/bin/bash

# Find the base directory
pushd `dirname $0` > /dev/null
BASE=`pwd -P`
popd > /dev/null

NATIVE_DIR=${BASE}/lib/native/`uname -m`
CLASSPATH=${BASE}/lib/itchy.jar:${BASE}/lib/jame.jar:${BASE}/lib/jython-2.5.3.jar:${BASE}/lib/groovy-all-2.3.6.jar
MAIN=uk.co.nickthecoder.itchy.Launcher

java -Ditchy.base="${BASE}" -Djava.library.path="${NATIVE_DIR}" -classpath "${CLASSPATH}" "${MAIN}" "$@"

#
# Register ".itchy" files, so that games can be run by double clicking their ".itchy" file.
#
if [[ "${BASE}/resources/Launcher/template.desktop" -nt "${BASE}/resources/Launcher/nickthecoder-itchy.desktop" ]]; then
    echo "Registering .itchy files"
    COMMAND="java -Ditchy.base=\"${BASE}\" -Djava.library.path=\"${NATIVE_DIR}\" -classpath \"${CLASSPATH}\" \"${MAIN}\""
    cp "${BASE}/resources/Launcher/template.desktop" "${BASE}/resources/Launcher/nickthecoder-itchy.desktop" > /dev/null 2>&1
    echo "Icon=${BASE}/resources/icon32.png" >> "${BASE}/resources/Launcher/nickthecoder-itchy.desktop"
    echo "Exec=${COMMAND} %u" >> "${BASE}/resources/Launcher/nickthecoder-itchy.desktop"
    xdg-icon-resource install --mode user --context mimetypes --size 32 "${BASE}/resources/icon32.png" application-x-itchy  > /dev/null 2>&1
    xdg-mime install --mode user "${BASE}/resources/Launcher/nickthecoder-itchy.xml" > /dev/null 2>&1
    xdg-desktop-menu install --mode user "${BASE}/resources/Launcher/nickthecoder-itchy.desktop" > /dev/null 2>&1
    xdg-mime default nickthecoder.itchy.desktop application/x-itchy  > /dev/null 2>&1
fi
