#!/bin/bash

# Find the base directory
pushd `dirname $0` > /dev/null
BASE=`pwd -P`
popd > /dev/null

NATIVE_DIR=${BASE}/lib/native/`uname -m`
CLASSPATH=${BASE}/lib/itchy.jar:${BASE}/lib/jame.jar
MAIN=uk.co.nickthecoder.itchy.Launcher

java -Ditchy.base="${BASE}" -Djava.library.path="${NATIVE_DIR}" -classpath "${CLASSPATH}" "${MAIN}" "$@"

